### ISSUE TITLE
Add country list: Turkey

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/website#683] opened 2021-09-20 17:48 UTC
The country "Turkey" is not available for selection. Admittedly, it is not a member of the EU (yet), but the current list of countries also includes non-members such as Norway, Switzerland or the United Kingdom.

**Comment by mal-tee** [comment] 2021-09-20 18:02
defacto duplicate of #682

**Closed by mal-tee** 2021-09-20 18:02 UTC
