### ISSUE TITLE
Display tested status if available on every detail site of a company record.

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/website#1067] opened 2023-06-07 16:29 UTC
Display tested status if available on every detail site of a company record.

> @WebworkrNet The tested status doesn't show up on company pages, only on other parts of the site like the search bar:

> ![image](https://github.com/datenanfragen/data/assets/4048809/f862e92d-7570-4478-a92d-8402d8222327)

> Only companies marked as `scraped` or `imported` have special rendering there, e.g. <https://www.datenanfragen.de/company/kirchengemeinde-zum-heiligen-leiden-christi-zu-braunschweig-stoeckheim>.

_Originally posted by @baltpeter in https://github.com/datenanfragen/data/pull/1960#issuecomment-1580080802_

**Comment by baltpeter** [comment] 2023-06-10 11:12
Duplicate of #784.

**Closed by baltpeter** 2023-06-10 11:12 UTC

**Comment by WebworkrNet** [comment] 2023-06-11 00:06
Sorry, @baltpeter .
